<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>Assets\app-icon.ico</ApplicationIcon>
    <AssemblyName>NBA2KJerseyModder</AssemblyName>
    <RootNamespace>JerseyModder.Wpf</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\app-icon.png" />
    <Resource Include="Assets\app-icon.ico" />
  </ItemGroup>
</Project>
