from __future__ import annotations

import argparse
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
import json
from pathlib import Path
import sys
from urllib.parse import unquote, urlparse

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from nba2k_jersey_modder.trim_web_session import TrimWebSession


SHARED_STYLE = r"""
:root{color-scheme:dark;font-family:"Segoe UI",Arial,sans-serif;--bg:#11151b;--panel:#1b212a;--line:#343d4b;--muted:#9da9ba;--accent:#f0b429}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:#eef2f7;overflow:hidden}header{height:58px;display:flex;align-items:center;gap:9px;padding:0 16px;background:#202731;border-bottom:1px solid var(--line)}header strong{font-size:17px}.spacer{flex:1}button,select,input{font:inherit}button{border:1px solid transparent;border-radius:5px;padding:8px 12px;background:#303947;color:#eef2f7;cursor:pointer;font-weight:600}button:hover{background:#3a4555}button.primary{background:var(--accent);color:#171a20}button.done{background:#2f7655;border-color:#4b9875;color:#fff}button.danger{color:#ffbdc5;border-color:#633742}.layout{height:calc(100vh - 58px);display:grid;grid-template-columns:minmax(0,1fr) 390px}.panel{background:var(--panel);border-left:1px solid var(--line);overflow:auto;padding:14px}.section{border-bottom:1px solid var(--line);padding-bottom:14px;margin-bottom:14px}h2{font-size:14px;margin:0 0 9px}.row{display:flex;gap:8px;align-items:center;margin:8px 0}.row>*{flex:1}label{display:block;color:#cbd3df;font-size:12px;margin-bottom:4px}select,input[type=number]{width:100%;background:#11161d;color:#eef2f7;border:1px solid #465163;border-radius:5px;padding:7px}.status{min-height:34px;color:#dce3ee;font-size:12px;line-height:1.4}.staged{display:flex;flex-direction:column;gap:7px;max-height:250px;overflow:auto}.stage-item{width:100%;display:grid;grid-template-columns:74px minmax(0,1fr);gap:9px;text-align:left;align-items:center;padding:6px;border:1px solid var(--line);background:#252d38}.stage-item.active{border-color:var(--accent);background:#30394a}.stage-item img{width:74px;height:44px;object-fit:contain;background:repeating-conic-gradient(#d8d8d8 0 25%,#fff 0 50%) 0/14px 14px}.stage-item b,.stage-item span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.stage-item span{color:var(--muted);font-size:11px;margin-top:3px}.empty{color:var(--muted);font-size:12px;padding:12px 2px}.checks{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin:11px 0}.checks label{display:flex;gap:7px;align-items:center}
"""


SELECTOR_HTML = r"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NBA 2K Trim Selector</title><style>__STYLE__
#stage{position:relative;min-width:0;min-height:0;background:#0d1015}canvas{width:100%;height:100%;display:block;cursor:crosshair}.hint{color:var(--muted);font-size:12px}
</style></head><body>
<header><strong>Trim Selector</strong><button id="zoomOut">Zoom -</button><button id="fit">Fit</button><button id="zoomIn">Zoom +</button><button id="clearLine">Clear Line</button><span class="spacer"></span><span class="hint">Click point one, then point two. Wheel zooms; middle-drag or Shift-drag pans.</span><button id="return" class="done">Done - Return to App</button></header>
<div class="layout"><main id="stage"><canvas id="canvas"></canvas></main><aside class="panel">
<section class="section"><h2>New Trim</h2><label>Trim type</label><select id="newType"></select><div class="row"><button id="stageTrim" class="primary">Stage Selected Line</button></div><div id="status" class="status">Loading mockup...</div></section>
<section class="section"><div class="row"><h2>Staged Trims</h2><button id="clearAll" class="danger">Clear All</button></div><div id="staged" class="staged"><div class="empty">No trims staged yet.</div></div><div class="row"><button id="openEditor">Open Staged Trim Editor</button></div></section>
</aside></div><script>
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d'),stage=$('stage'),image=new Image();let project=null,points=[],scale=1,minScale=1,panX=0,panY=0,panning=false,panStart=null;
async function api(path,payload){const options=payload===undefined?{cache:'no-store'}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)};const response=await fetch(path,options),data=await response.json();if(!response.ok)throw new Error(data.error||`Request failed: ${response.status}`);return data}function status(text){$('status').textContent=text}
async function load(initial=false){project=await api('/api/project');fillTypes();renderList();if(initial){image.onload=()=>{fit();status('Click the first point, then the second point across the trim.');};image.onerror=()=>status('The mockup could not be displayed.');image.src=`${project.imageUrl}?v=${project.sourceVersion}`}}
function fillTypes(){const current=$('newType').value;$('newType').innerHTML='';project.trimTypes.forEach(item=>{const option=document.createElement('option');option.value=item.target;option.textContent=item.label;$('newType').append(option)});if(current)$('newType').value=current}
function renderList(){const host=$('staged');host.innerHTML='';if(!project.items.length){host.innerHTML='<div class="empty">No trims staged yet.</div>';return}project.items.forEach((item,index)=>{const button=document.createElement('button');button.className='stage-item'+(item.id===project.selectedId?' active':'');button.innerHTML=`<img src="${item.previewUrl}?v=${Date.now()}" alt=""><div><b>${index+1}. ${item.typeLabel}</b><span>${item.angle} degrees</span></div>`;button.onclick=async()=>{project=await api('/api/select',{id:item.id});renderList()};host.append(button)})}
function resize(){const ratio=devicePixelRatio||1;canvas.width=Math.max(1,stage.clientWidth*ratio);canvas.height=Math.max(1,stage.clientHeight*ratio);ctx.setTransform(ratio,0,0,ratio,0,0);draw()}function fit(){minScale=Math.max(.03,Math.min(1,(stage.clientWidth-36)/project.width,(stage.clientHeight-36)/project.height));scale=minScale;panX=(stage.clientWidth-project.width*scale)/2;panY=(stage.clientHeight-project.height*scale)/2;draw()}function draw(){ctx.clearRect(0,0,stage.clientWidth,stage.clientHeight);ctx.fillStyle='#0d1015';ctx.fillRect(0,0,stage.clientWidth,stage.clientHeight);if(!project||!image.complete)return;ctx.drawImage(image,panX,panY,project.width*scale,project.height*scale);if(!points.length)return;ctx.save();ctx.strokeStyle='#ffd05a';ctx.fillStyle='#ffd05a';ctx.lineWidth=3;const screen=points.map(p=>({x:panX+p.x*scale,y:panY+p.y*scale}));if(screen.length===2){ctx.beginPath();ctx.moveTo(screen[0].x,screen[0].y);ctx.lineTo(screen[1].x,screen[1].y);ctx.stroke()}screen.forEach((p,i)=>{ctx.beginPath();ctx.arc(p.x,p.y,7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#171a20';ctx.font='bold 11px Segoe UI';ctx.textAlign='center';ctx.fillText(String(i+1),p.x,p.y+4);ctx.fillStyle='#ffd05a'});ctx.restore()}
function cp(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}function ip(e){const p=cp(e);return{x:Math.max(0,Math.min(project.width-1,Math.round((p.x-panX)/scale))),y:Math.max(0,Math.min(project.height-1,Math.round((p.y-panY)/scale)))}}function zoom(f,c){const bx=(c.x-panX)/scale,by=(c.y-panY)/scale;scale=Math.max(minScale*.5,Math.min(12,scale*f));panX=c.x-bx*scale;panY=c.y-by*scale;draw()}
canvas.onpointerdown=e=>{if(e.shiftKey||e.button===1||e.button===2){panning=true;const p=cp(e);panStart={x:p.x,y:p.y,panX,panY};canvas.setPointerCapture(e.pointerId);return}const p=ip(e);if(points.length>=2)points=[];points.push(p);if(points.length===1)status(`Point 1: ${p.x}, ${p.y}. Click point 2.`);else{const a=points[0],angle=Math.atan2(p.y-a.y,p.x-a.x)*180/Math.PI,length=Math.hypot(p.x-a.x,p.y-a.y);status(`Line ready: ${angle.toFixed(1)} degrees, ${length.toFixed(0)} pixels.`)}draw()};canvas.onpointermove=e=>{if(!panning||!panStart)return;const p=cp(e);panX=panStart.panX+p.x-panStart.x;panY=panStart.panY+p.y-panStart.y;draw()};canvas.onpointerup=()=>{panning=false;panStart=null};canvas.onwheel=e=>{e.preventDefault();zoom(e.deltaY<0?1.16:1/1.16,cp(e))};canvas.oncontextmenu=e=>e.preventDefault();
$('stageTrim').onclick=async()=>{if(points.length<2){status('Click two points across the trim first.');return}const button=$('stageTrim');button.disabled=true;status('Creating straight trim strip...');try{project=await api('/api/stage',{start:points[0],end:points[1],target:$('newType').value});const item=project.items.find(x=>x.id===project.selectedId);points=[];draw();renderList();status(`Staged ${item.typeLabel}. Select another line from the same mockup.`)}catch(e){status(e.message)}finally{button.disabled=false}};$('clearLine').onclick=()=>{points=[];draw();status('Line cleared. Click point one, then point two.')} ;$('clearAll').onclick=async()=>{if(!project.items.length||!confirm('Remove every staged trim?'))return;project=await api('/api/clear',{});renderList();status('Cleared staged trims.')} ;$('openEditor').onclick=()=>location.href='/edit';$('fit').onclick=fit;$('zoomIn').onclick=()=>zoom(1.25,{x:stage.clientWidth/2,y:stage.clientHeight/2});$('zoomOut').onclick=()=>zoom(1/1.25,{x:stage.clientWidth/2,y:stage.clientHeight/2});$('return').onclick=async()=>{const b=$('return');b.disabled=true;const result=await api('/api/return',{});status(`${result.items} staged trim${result.items===1?'':'s'} saved. Returning to the app...`);b.textContent='App Ready - Close This Tab';setTimeout(()=>window.close(),350)};window.onresize=resize;resize();load(true).catch(e=>status(e.message));
</script></body></html>""".replace("__STYLE__", SHARED_STYLE)


EDITOR_HTML = r"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NBA 2K Staged Trim Editor</title><style>__STYLE__
#previewStage{min-width:0;min-height:0;padding:34px;display:grid;place-items:center;background:repeating-conic-gradient(#d5d8dc 0 25%,#f5f6f7 0 50%) 0/28px 28px}#preview{width:min(92%,1200px);max-height:72%;object-fit:contain;image-rendering:auto;filter:drop-shadow(0 8px 18px rgba(0,0,0,.2))}#emptyPreview{color:#4c5664;font-size:16px;font-weight:600}
</style></head><body><header><strong>Staged Trim Editor</strong><button id="selector">Back to Trim Selector</button><span class="spacer"></span><button id="return" class="done">Done - Return to App</button></header><div class="layout"><main id="previewStage"><div id="emptyPreview">Select a staged trim to edit.</div><img id="preview" alt="Selected staged trim" hidden></main><aside class="panel">
<section class="section"><div class="row"><h2>Staged Trims</h2><button id="clear" class="danger">Clear All</button></div><div id="staged" class="staged"><div class="empty">No trims staged.</div></div></section>
<section id="controls" hidden><h2>Selected Trim</h2><label>Trim type</label><select id="type"></select><div class="row"><div><label>Crop top (-32 to 63)</label><input id="cropTop" type="number" min="-32" max="63" value="0"></div><div><label>Crop bottom (-32 to 63)</label><input id="cropBottom" type="number" min="-32" max="63" value="0"></div></div><div class="checks"><label><input id="correct" type="checkbox" checked> Even lines and gaps</label><label><input id="sharpen" type="checkbox"> Sharpen</label><label><input id="color" type="checkbox"> Color correction</label></div><label>Upscale</label><select id="scale"><option value="1">1x (original pixels)</option><option value="2">2x</option><option value="4">4x</option></select><div class="row"><button id="apply" class="primary">Apply Changes</button><button id="remove" class="danger">Remove Trim</button></div></section><div id="status" class="status">Loading staged trims...</div>
</aside></div><script>
const $=id=>document.getElementById(id);let project=null,selected=null;async function api(path,payload){const options=payload===undefined?{cache:'no-store'}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)};const response=await fetch(path,options),data=await response.json();if(!response.ok)throw new Error(data.error||`Request failed: ${response.status}`);return data}function status(t){$('status').textContent=t}async function load(){project=await api('/api/project');selected=project.items.find(x=>x.id===project.selectedId)||project.items[0]||null;if(selected&&selected.id!==project.selectedId)project=await api('/api/select',{id:selected.id});fillTypes();render();status(project.items.length?`${project.items.length} staged trim${project.items.length===1?'':'s'} ready to edit.`:'Return to the selector to stage a trim.')}function fillTypes(){const current=$('type').value;$('type').innerHTML='';project.trimTypes.forEach(item=>{const o=document.createElement('option');o.value=item.target;o.textContent=item.label;$('type').append(o)});if(current)$('type').value=current}function render(){list();const has=!!selected;$('controls').hidden=!has;$('preview').hidden=!has;$('emptyPreview').hidden=has;if(!has)return;$('preview').src=`${selected.previewUrl}?v=${Date.now()}`;$('type').value=selected.target;$('cropTop').value=selected.cropTop;$('cropBottom').value=selected.cropBottom;$('correct').checked=selected.correct;$('sharpen').checked=selected.sharpen;$('color').checked=selected.colorCorrect;$('scale').value=selected.scale}function list(){const host=$('staged');host.innerHTML='';if(!project.items.length){host.innerHTML='<div class="empty">No trims staged.</div>';return}project.items.forEach((item,index)=>{const b=document.createElement('button');b.className='stage-item'+(item.id===selected?.id?' active':'');b.innerHTML=`<img src="${item.previewUrl}?v=${Date.now()}" alt=""><div><b>${index+1}. ${item.typeLabel}</b><span>${item.angle} degrees</span></div>`;b.onclick=async()=>{project=await api('/api/select',{id:item.id});selected=project.items.find(x=>x.id===item.id);render();status(`Editing ${selected.typeLabel}.`)};host.append(b)})}
$('apply').onclick=async()=>{if(!selected)return;const b=$('apply');b.disabled=true;status('Regenerating from the original mockup...');try{project=await api('/api/update',{id:selected.id,target:$('type').value,cropTop:+$('cropTop').value,cropBottom:+$('cropBottom').value,correct:$('correct').checked,sharpen:$('sharpen').checked,colorCorrect:$('color').checked,scale:+$('scale').value});selected=project.items.find(x=>x.id===project.selectedId);render();status('Trim changes applied from the original selected line.')}catch(e){status(e.message)}finally{b.disabled=false}};$('remove').onclick=async()=>{if(!selected)return;project=await api('/api/remove',{id:selected.id});selected=project.items.find(x=>x.id===project.selectedId)||null;render();status('Removed staged trim.')} ;$('clear').onclick=async()=>{if(!project.items.length||!confirm('Remove every staged trim?'))return;project=await api('/api/clear',{});selected=null;render();status('Cleared staged trims.')} ;$('selector').onclick=()=>location.href='/';$('return').onclick=async()=>{const b=$('return');b.disabled=true;const result=await api('/api/return',{});status(`${result.items} staged trim${result.items===1?'':'s'} saved. Returning to the app...`);b.textContent='App Ready - Close This Tab';setTimeout(()=>window.close(),350)};load().catch(e=>status(e.message));
</script></body></html>""".replace("__STYLE__", SHARED_STYLE)


def handler_class(session: TrimWebSession):
    class Handler(BaseHTTPRequestHandler):
        def log_message(self, _format, *args): return
        def do_GET(self):  # noqa: N802
            try:
                path = urlparse(self.path).path
                if path in ("/", "/trim"): self._send(SELECTOR_HTML.encode(), "text/html; charset=utf-8")
                elif path == "/edit": self._send(EDITOR_HTML.encode(), "text/html; charset=utf-8")
                elif path == "/api/project": self._json(session.project())
                elif path == "/api/reference": self._send(*session.reference_bytes())
                elif path.startswith("/api/preview/"): self._send(*session.preview_bytes(unquote(path.rsplit("/",1)[1])))
                else: self.send_error(404)
            except Exception as exc: self._json({"error":str(exc)},500)
        def do_POST(self):  # noqa: N802
            try:
                length=int(self.headers.get("Content-Length","0"));payload=json.loads(self.rfile.read(length) or b"{}")
                action={"/api/stage":lambda:session.stage(payload),"/api/import":lambda:session.import_image(payload),"/api/update":lambda:session.update(payload),"/api/select":lambda:session.select(payload),"/api/remove":lambda:session.remove(payload),"/api/clear":session.clear,"/api/return":session.request_return}.get(urlparse(self.path).path)
                if action is None:self.send_error(404);return
                self._json(action())
            except Exception as exc:self._json({"error":str(exc)},400)
        def _json(self,value,status=200):self._send(json.dumps(value).encode(),"application/json",status)
        def _send(self,data,content_type,status=200):
            self.send_response(status);self.send_header("Content-Type",content_type);self.send_header("Content-Length",str(len(data)));self.send_header("Cache-Control","no-store" if content_type=="application/json" else "private, max-age=3600");self.end_headers();self.wfile.write(data)
    return Handler


def main():
    parser=argparse.ArgumentParser();parser.add_argument("--reference",required=True);parser.add_argument("--state",required=True);args=parser.parse_args()
    session=TrimWebSession(Path(args.reference),Path(args.state));server=ThreadingHTTPServer(("127.0.0.1",0),handler_class(session));url=f"http://127.0.0.1:{server.server_port}/";print(json.dumps({"url":url}),flush=True);server.serve_forever()


if __name__=="__main__":main()
