using System.Collections.ObjectModel;
using System.IO;
using System.Text.Json.Nodes;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Threading;
using JerseyModder.Wpf.Controls;
using JerseyModder.Wpf.Services;
using Microsoft.Win32;

namespace JerseyModder.Wpf.Views;

public sealed class TextureCreatorPage : ToolPageBase
{
    private readonly ImageViewport _preview=new();private readonly ComboBox _kind=new();private readonly Slider _strength=new(){Minimum=0,Maximum=100,Value=15};private readonly TextBlock _strengthText=new(){Text="15%"};private readonly DispatcherTimer _timer=new(){Interval=TimeSpan.FromMilliseconds(140)};private string? _rendered;
    public TextureCreatorPage(WorkspaceContext context):base(context){foreach(var x in new[]{"Color Texture","Region Texture","Normal Map"})_kind.Items.Add(x);_kind.SelectedIndex=0;var controls=new StackPanel();controls.Children.Add(Ui.Row("Texture",_kind));controls.Children.Add(Ui.Row("Logo strength",Pair(_strength,_strengthText)));controls.Children.Add(Ui.Button("Update Preview",async(_,_)=>await RefreshAsync(),true));controls.Children.Add(Ui.Buttons(Ui.Button("Save PNG As",OnSavePng),Ui.Button("Save DDS BC1 As",OnSaveDds)));controls.Children.Add(Ui.Button("Save Layered PSD As",OnSavePsd));_kind.SelectionChanged+=(_,_)=>Schedule();_strength.ValueChanged+=(_,_)=>{_strengthText.Text=$"{_strength.Value:0}%";Schedule();};_timer.Tick+=async(_,_)=>{_timer.Stop();await RefreshAsync();};Content=Ui.Page("Texture Creator","Preview and export color, region, and normal textures from the current project.",Ui.Split(_preview,new ScrollViewer{Content=controls,VerticalScrollBarVisibility=ScrollBarVisibility.Auto},390));Loaded+=async(_,_)=>await RefreshAsync();Context.Project.Changed+=(_,_)=>Schedule();}
    private static Grid Pair(UIElement a,UIElement b){var g=new Grid();g.ColumnDefinitions.Add(new ColumnDefinition());g.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(46)});Grid.SetColumn(b,1);g.Children.Add(a);g.Children.Add(b);return g;}
    protected override async void OnProjectReplaced()=>await RefreshAsync();private void Schedule(){_timer.Stop();_timer.Start();}
    private async Task RefreshAsync(){try{var result=(await Context.Bridge.CallAsync("render",new{project=Context.Project.Snapshot(),kind=_kind.SelectedItem?.ToString(),strength=(int)_strength.Value}))!.AsObject();_rendered=result["path"]?.GetValue<string>();_preview.Load(_rendered);Status($"Updated {_kind.SelectedItem?.ToString()?.ToLowerInvariant()} preview.");}catch(Exception ex){Status(ex.Message);}}
    private void OnSavePng(object s,RoutedEventArgs e)=>Save(".png","PNG image|*.png");private void OnSaveDds(object s,RoutedEventArgs e)=>Save(".dds","DDS BC1|*.dds");private void OnSavePsd(object s,RoutedEventArgs e)=>Save(".psd","Photoshop document|*.psd");
    private async void Save(string extension,string filter){var d=new SaveFileDialog{Filter=filter,FileName="texture"+extension};if(d.ShowDialog()!=true)return;try{await Context.Bridge.CallAsync("save_texture",new{project=Context.Project.Snapshot(),path=d.FileName,kind=_kind.SelectedItem?.ToString(),format=extension,strength=(int)_strength.Value});Status($"Saved {Path.GetFileName(d.FileName)}.");}catch(Exception ex){Error("Texture Creator",ex);}}
}

public sealed class IffTexturesPage : ToolPageBase
{
    private readonly ObservableCollection<IffRow> _rows=new();private readonly DataGrid _grid=new(){AutoGenerateColumns=false,IsReadOnly=true,SelectionMode=DataGridSelectionMode.Single};private string? _source;private readonly Dictionary<int,string> _replacements=new();
    private sealed class IffRow{public int Index{get;init;}public string Texture{get;init;}="";public string Dds{get;init;}="";public string Txtr{get;init;}="";public string Status{get;init;}="";public string Replacement{get;set;}="";public JsonObject? DdsHit{get;init;}public JsonObject? TxtrHit{get;init;}}
    public IffTexturesPage(WorkspaceContext context):base(context){foreach(var c in new[]{("Texture","Texture",240d),("DDS","Dds",220d),("TXTR","Txtr",220d),("Status","Status",130d),("Replacement","Replacement",220d)})_grid.Columns.Add(new DataGridTextColumn{Header=c.Item1,Binding=new System.Windows.Data.Binding(c.Item2),Width=c.Item3});_grid.ItemsSource=_rows;var body=new Grid();body.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});body.RowDefinitions.Add(new RowDefinition());var bar=Ui.Buttons(Ui.Button("Import IFF",OnOpen,true),Ui.Button("Export DDS",async(_,_)=>await ExportAsync(true)),Ui.Button("Export TXTR",async(_,_)=>await ExportAsync(false)),Ui.Button("Choose Replacement DDS",OnReplace),Ui.Button("Save Modified IFF As",OnSave));body.Children.Add(bar);Grid.SetRow(_grid,1);body.Children.Add(_grid);Content=Ui.Page("IFF Textures","Inspect DDS and TXTR resources once, side by side, then export or replace safe entries.",body);}
    private async void OnOpen(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="IFF|*.iff|All files|*.*"};if(d.ShowDialog()!=true)return;try{var result=(await Context.Bridge.CallAsync("iff_scan",new{path=d.FileName}))!.AsObject();_source=d.FileName;_rows.Clear();_replacements.Clear();var i=0;foreach(var n in result["pairs"]!.AsArray()){var o=n!.AsObject();_rows.Add(new IffRow{Index=i++,Texture=o["key"]?.GetValue<string>()??"",Dds=o["dds"]?["name"]?.GetValue<string>()??"",Txtr=o["txtr"]?["name"]?.GetValue<string>()??"",Status=o["status"]?.GetValue<string>()??"",DdsHit=o["dds"] as JsonObject,TxtrHit=o["txtr"] as JsonObject});}Status($"Loaded {Path.GetFileName(_source)}: {_rows.Count} texture pair(s).");}catch(Exception ex){Error("IFF Textures",ex);}}
    private async Task ExportAsync(bool dds){if(_source is null||_grid.SelectedItem is not IffRow row)return;var hit=dds?row.DdsHit:row.TxtrHit;if(hit is null)return;var name=dds?row.Dds:row.Txtr;var d=new SaveFileDialog{FileName=name,Filter="All files|*.*"};if(d.ShowDialog()!=true)return;try{await Context.Bridge.CallAsync("iff_export",new{source=_source,hit,destination=d.FileName});Status($"Exported {Path.GetFileName(d.FileName)}.");}catch(Exception ex){Error("IFF Textures",ex);}}
    private void OnReplace(object s,RoutedEventArgs e){if(_grid.SelectedItem is not IffRow row||row.DdsHit is null)return;var d=new OpenFileDialog{Filter="DDS|*.dds"};if(d.ShowDialog()!=true)return;_replacements[row.Index]=d.FileName;row.Replacement=Path.GetFileName(d.FileName);_grid.Items.Refresh();}
    private async void OnSave(object s,RoutedEventArgs e){if(_source is null||_replacements.Count==0)return;var d=new SaveFileDialog{Filter="IFF|*.iff",FileName=Path.GetFileNameWithoutExtension(_source)+"_modified.iff"};if(d.ShowDialog()!=true)return;try{var replacements=_replacements.Select(pair=>new{hit=_rows[pair.Key].DdsHit,path=pair.Value}).ToArray();await Context.Bridge.CallAsync("iff_replace",new{source=_source,destination=d.FileName,replacements});Status($"Saved {Path.GetFileName(d.FileName)}.");}catch(Exception ex){Error("IFF Textures",ex);}}
}

public sealed class RdatEditorPage : ToolPageBase
{
    private readonly TextBox _editor=new(){AcceptsReturn=true,AcceptsTab=true,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Auto,FontFamily=new System.Windows.Media.FontFamily("Consolas"),TextWrapping=TextWrapping.NoWrap};private string? _source,_entry,_encoding;
    public RdatEditorPage(WorkspaceContext context):base(context){var body=new Grid();body.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});body.RowDefinitions.Add(new RowDefinition());body.Children.Add(Ui.Buttons(Ui.Button("Open RDAT or IFF",OnOpen,true),Ui.Button("Save",async(_,_)=>await SaveAsync(false)),Ui.Button("Save As",async(_,_)=>await SaveAsync(true))));Grid.SetRow(_editor,1);body.Children.Add(_editor);Content=Ui.Page("RDAT Editor","Edit loose RDAT text or an RDAT entry stored inside an archive-style IFF.",body);}
    private async void OnOpen(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="RDAT / IFF|*.rdat;*.iff|All files|*.*"};if(d.ShowDialog()!=true)return;try{var result=(await Context.Bridge.CallAsync("rdat_read",new{path=d.FileName}))!.AsObject();_source=d.FileName;_entry=result["entry"]?.GetValue<string>();_encoding=result["encoding"]?.GetValue<string>()??"utf-8";_editor.Text=result["text"]?.GetValue<string>()??"";Status($"Loaded {_entry??Path.GetFileName(_source)} ({_encoding}).");}catch(Exception ex){Error("RDAT Editor",ex);}}
    private async Task SaveAsync(bool saveAs){if(_source is null)return;var destination=_source;if(saveAs){var d=new SaveFileDialog{Filter="RDAT / IFF|*.rdat;*.iff",FileName=Path.GetFileName(_source)};if(d.ShowDialog()!=true)return;destination=d.FileName;}try{await Context.Bridge.CallAsync("rdat_write",new{source=_source,destination,entry=_entry,encoding=_encoding,text=_editor.Text});_source=destination;Status($"Saved {Path.GetFileName(destination)}.");}catch(Exception ex){Error("RDAT Editor",ex);}}
}

public sealed class TemplateEditorPage : ToolPageBase
{
    private readonly ComboBox _garment=new(),_variant=new(),_map=new();private readonly ImageViewport _preview=new();private readonly ObservableCollection<ZoneRow> _zones=new();private readonly DataGrid _grid=new(){AutoGenerateColumns=false,CanUserAddRows=false,IsReadOnly=false};private readonly TextBlock _coordinates=new(){Text="Mouse: --",Foreground=(System.Windows.Media.Brush)Application.Current.Resources["MutedBrush"]};private string? _zonesPath,_imagePath;
    private sealed class ZoneRow{public string Name{get;set;}="";public string Type{get;set;}="";public int X{get;set;}public int Y{get;set;}public int Width{get;set;}public int Height{get;set;}public string Hex{get;set;}="#ffffff";public int Layer{get;set;}public JsonObject Json()=>new(){{"name",Name},{"zone_type",Type},{"x",X},{"y",Y},{"width",Width},{"height",Height},{"color",Hex},{"layer",Layer}};}
    public TemplateEditorPage(WorkspaceContext context):base(context){foreach(var x in new[]{"Jersey","Shorts"})_garment.Items.Add(x);_garment.SelectedIndex=0;foreach(var c in new[]{("Name","Name",150d),("Type","Type",95d),("X","X",65d),("Y","Y",65d),("Width","Width",70d),("Height","Height",70d),("Hex","Hex",90d),("Layer","Layer",60d)})_grid.Columns.Add(new DataGridTextColumn{Header=c.Item1,Binding=new System.Windows.Data.Binding(c.Item2),Width=c.Item3});_grid.ItemsSource=_zones;_preview.ImagePointClicked+=(_,p)=>_coordinates.Text=$"Mouse: X {p.X:0} | Y {p.Y:0}";_garment.SelectionChanged+=(_,_)=>Populate();
        var body=new Grid();body.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});body.RowDefinitions.Add(new RowDefinition());var top=new StackPanel{Orientation=Orientation.Horizontal,Margin=new Thickness(0,0,0,9)};top.Children.Add(new TextBlock{Text="Garment",VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(0,0,5,0)});_garment.Width=110;top.Children.Add(_garment);top.Children.Add(new TextBlock{Text="Template",VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(10,0,5,0)});_variant.Width=140;top.Children.Add(_variant);top.Children.Add(new TextBlock{Text="Map",VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(10,0,5,0)});_map.Width=150;top.Children.Add(_map);top.Children.Add(Ui.Button("Load Master",async(_,_)=>await LoadAsync(),true));top.Children.Add(Ui.Button("Save Zones As",OnSave));top.Children.Add(Ui.Button("Add Zone",(_,_)=>_zones.Add(new ZoneRow{Name=$"new_zone_{_zones.Count+1}",Type="custom",Width=100,Height=100})));top.Children.Add(Ui.Button("Remove Zone",(_,_)=>{if(_grid.SelectedItem is ZoneRow z)_zones.Remove(z);}));body.Children.Add(top);var left=new Grid();left.RowDefinitions.Add(new RowDefinition());left.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});left.Children.Add(_preview);Grid.SetRow(_coordinates,1);left.Children.Add(_coordinates);var split=Ui.Split(left,_grid,590);Grid.SetRow(split,1);body.Children.Add(split);Content=Ui.Page("Template Editor","Maintain color-coded template zones and exact 2048 coordinate data. This advanced source editor is optional.",body);Populate();Loaded+=async(_,_)=>await LoadAsync();}
    private void Populate(){_variant.Items.Clear();_map.Items.Clear();if(_garment.SelectedItem?.ToString()=="Shorts"){foreach(var x in new[]{"Retro shorts","Classic shorts","Modern shorts"})_variant.Items.Add(x);foreach(var x in new[]{"Shorts color","Shorts UV","Shorts normal"})_map.Items.Add(x);}else{_variant.Items.Add("Retro U");foreach(var x in new[]{"Jersey color","Jersey region","Jersey normal","Jersey UV"})_map.Items.Add(x);}_variant.SelectedIndex=0;_map.SelectedIndex=0;}
    private async Task LoadAsync(){if(_garment.SelectedItem is null||_variant.SelectedItem is null||_map.SelectedItem is null)return;try{var result=(await Context.Bridge.CallAsync("template_load",new{garment=_garment.SelectedItem.ToString(),variant=_variant.SelectedItem.ToString(),map=_map.SelectedItem.ToString()}))!.AsObject();_imagePath=result["image"]?.GetValue<string>();_zonesPath=result["zonesPath"]?.GetValue<string>();_preview.Load(_imagePath);_zones.Clear();foreach(var n in result["zones"]!.AsArray()){var o=n!.AsObject();_zones.Add(new ZoneRow{Name=o["name"]?.GetValue<string>()??"",Type=o["zone_type"]?.GetValue<string>()??"",X=o["x"]?.GetValue<int>()??0,Y=o["y"]?.GetValue<int>()??0,Width=o["width"]?.GetValue<int>()??0,Height=o["height"]?.GetValue<int>()??0,Hex=o["color"]?.GetValue<string>()??"#ffffff",Layer=o["layer"]?.GetValue<int>()??0});}Status($"Loaded {_variant.SelectedItem} {_map.SelectedItem} master.");}catch(Exception ex){Error("Template Editor",ex);}}
    private async void OnSave(object s,RoutedEventArgs e){var d=new SaveFileDialog{Filter="Template zones|*.json",FileName=Path.GetFileName(_zonesPath??"template.zones.json")};if(d.ShowDialog()!=true)return;try{await Context.Bridge.CallAsync("template_save",new{path=d.FileName,image=_imagePath,zones=_zones.Select(z=>z.Json()).ToArray()});Status($"Saved {_zones.Count} zones.");}catch(Exception ex){Error("Template Editor",ex);}}
}
