using System.IO;
using System.Text.Json.Nodes;
using System.Windows;
using System.Windows.Controls;
using JerseyModder.Wpf.Controls;
using JerseyModder.Wpf.Services;
using Microsoft.Win32;

namespace JerseyModder.Wpf.Views;

public sealed class LogoCreatorPage : ToolPageBase
{
    private readonly ImageViewport _reference = new(), _preview = new();
    private readonly TextBlock _selection = new() { Foreground = (System.Windows.Media.Brush)Application.Current.Resources["MutedBrush"] };
    private readonly ComboBox _type = new(); private readonly Slider _tolerance = new() { Minimum = 0, Maximum = 255, Value = 32 };
    private readonly ComboBox _upscale = new(); private readonly CheckBox _auto = new() { Content="Auto background" }, _white = new() { Content="Remove white" }, _black = new() { Content="Remove black" }, _outside = new() { Content="Outside only", IsChecked=true };
    private readonly ListBox _stagedList = new(); private readonly List<Point> _points = new(); private readonly List<(string Path,string Target)> _staged = new();
    private string? _source, _current;

    public LogoCreatorPage(WorkspaceContext context) : base(context)
    {
        _reference.ImagePointClicked += (_, p) => Point(p); var left = new Grid(); left.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});left.RowDefinitions.Add(new RowDefinition());left.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});
        var open=Ui.Button("Upload Reference Photo",OnOpen,true);left.Children.Add(open);Grid.SetRow(_reference,1);left.Children.Add(_reference);Grid.SetRow(_selection,2);_selection.Margin=new Thickness(0,7,0,0);left.Children.Add(_selection);
        var right=new StackPanel();_preview.Height=285;right.Children.Add(_preview);
        foreach(var item in new[]{"Center Chest Logo","Left Chest Logo","Right Chest Logo","Front Wordmark","Wrap Logo","Back Neck Logo","Back Center Logo","Belt Buckle Logo"})_type.Items.Add(item);_type.SelectedIndex=0;right.Children.Add(Ui.Row("Logo type",_type));
        var checks=new WrapPanel{Margin=new Thickness(0,4,0,5)};foreach(var c in new[]{_auto,_white,_black,_outside})checks.Children.Add(c);right.Children.Add(new GroupBox{Header="Cleanup",Content=checks});
        right.Children.Add(Ui.Row("Tolerance",_tolerance));_upscale.Items.Add("1x");_upscale.Items.Add("2x");_upscale.Items.Add("4x");_upscale.SelectedIndex=2;right.Children.Add(Ui.Row("Upscale",_upscale));
        right.Children.Add(Ui.Buttons(Ui.Button("Refresh Logo Preview",OnProcess,true)));right.Children.Add(Ui.Buttons(Ui.Button("Stage Current Logo",OnStage),Ui.Button("Send Staged to Generator",OnSend)));
        _stagedList.Height=130;right.Children.Add(new GroupBox{Header="Staged Logos",Content=_stagedList});right.Children.Add(Ui.Button("Clear Staged",(_,_)=>{_staged.Clear();RefreshStaged();}));
        Content=Ui.Page("Logo Creator","Select, straighten, clean, upscale, and stage transparent logos before placing them on a uniform.",Ui.Split(left,new ScrollViewer{Content=right,VerticalScrollBarVisibility=ScrollBarVisibility.Auto}));
    }
    private void OnOpen(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="Images|*.png;*.jpg;*.jpeg;*.bmp;*.webp|All files|*.*"};if(d.ShowDialog()!=true)return;_source=d.FileName;_points.Clear();_reference.Load(_source);_selection.Text="Click the top-left and bottom-right of the logo.";}
    private void Point(Point p){if(_source is null)return;_points.Add(p);while(_points.Count>2)_points.RemoveAt(0);_selection.Text=_points.Count==1?$"First point: {p.X:0}, {p.Y:0}":$"Selection: {_points[0].X:0}, {_points[0].Y:0} to {_points[1].X:0}, {_points[1].Y:0}";if(_points.Count==2)_=ProcessAsync();}
    private void OnProcess(object s,RoutedEventArgs e)=>_=ProcessAsync();
    private async Task ProcessAsync(){if(_source is null)return;try{object? box=_points.Count==2?new[]{(int)_points[0].X,(int)_points[0].Y,(int)_points[1].X,(int)_points[1].Y}:null;var result=(await Context.Bridge.CallAsync("logo_process",new{path=_source,box,auto=_auto.IsChecked==true,removeWhite=_white.IsChecked==true,removeBlack=_black.IsChecked==true,outsideOnly=_outside.IsChecked==true,tolerance=(int)_tolerance.Value,scale=_upscale.SelectedIndex switch{1=>2,2=>4,_=>1}}))!.AsObject();_current=result["path"]?.GetValue<string>();_preview.Load(_current);Status("Logo preview updated.");}catch(Exception ex){Error("Logo Creator",ex);}}
    private void OnStage(object s,RoutedEventArgs e){if(_current is null)return;_staged.Add((_current,Target()));RefreshStaged();}
    private string Target()=>new[]{"front_center_chest_logo","front_left_chest_logo","front_right_chest_logo","front_wordmark","wrap_across_front_back_logo","back_neck_logo","back_center_logo","shorts_belt_buckle_logo"}[Math.Max(0,_type.SelectedIndex)];
    private void RefreshStaged(){_stagedList.ItemsSource=null;_stagedList.ItemsSource=_staged.Select(x=>$"{x.Target} | {Path.GetFileName(x.Path)}").ToList();}
    private void OnSend(object s,RoutedEventArgs e){var logos=(JsonArray)Context.Project.Generator["logos"]!;foreach(var item in _staged)logos.Add(new JsonObject{{"path",item.Path},{"targetName",item.Target},{"offsetX",0},{"offsetY",0},{"scalePercent",100},{"scaleWidthPercent",100},{"scaleHeightPercent",100},{"rotationDegrees",0}});if(_staged.Count>0){Context.Project.MarkChanged();Status($"Sent {_staged.Count} staged logo(s) to Generator.");}}
}

public sealed class TrimCreatorPage : ToolPageBase
{
    private readonly ImageViewport _reference=new(),_preview=new();private readonly TextBlock _readout=new(){Foreground=(System.Windows.Media.Brush)Application.Current.Resources["MutedBrush"]};private readonly ComboBox _type=new();private readonly CheckBox _correct=new(){Content="Correct uneven lines and small gaps",IsChecked=true},_sharpen=new(){Content="Sharpen"},_color=new(){Content="Color correction"};private readonly ListBox _list=new();private readonly List<Point> _points=new();private readonly List<(string Path,string Type)> _staged=new();private string? _source,_current;
    public TrimCreatorPage(WorkspaceContext context):base(context){_reference.ImagePointClicked+=(_,p)=>Point(p);var left=new Grid();left.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});left.RowDefinitions.Add(new RowDefinition());left.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});left.Children.Add(Ui.Button("Upload Jersey Mockup",OnOpen,true));Grid.SetRow(_reference,1);left.Children.Add(_reference);Grid.SetRow(_readout,2);_readout.Margin=new Thickness(0,7,0,0);left.Children.Add(_readout);
        var right=new StackPanel();_preview.Height=220;right.Children.Add(_preview);foreach(var item in new[]{"Collar Trim","Left Arm Hole Trim","Right Arm Hole Trim","Waistband"})_type.Items.Add(item);_type.SelectedIndex=0;right.Children.Add(Ui.Row("Trim type",_type));var cleanup=new StackPanel();cleanup.Children.Add(_correct);cleanup.Children.Add(_sharpen);cleanup.Children.Add(_color);right.Children.Add(new GroupBox{Header="Cleanup",Content=cleanup});right.Children.Add(Ui.Buttons(Ui.Button("Stage Current Trim",OnStage,true),Ui.Button("Send Staged to Generator",OnSend)));right.Children.Add(Ui.Buttons(Ui.Button("Edit Selected Trim",(_,_)=>LoadSelected()),Ui.Button("Save Trim PNG As",OnSave)));_list.Height=120;right.Children.Add(new GroupBox{Header="Staged Trims",Content=_list});right.Children.Add(Ui.Buttons(Ui.Button("Remove Selected",OnRemove),Ui.Button("Clear",(_,_)=>{_staged.Clear();Refresh();})));Content=Ui.Page("Trim Creator","Upload a uniform photo, click two precise points across a trim, and create a new straight transparent trim strip.",Ui.Split(left,new ScrollViewer{Content=right,VerticalScrollBarVisibility=ScrollBarVisibility.Auto}));}
    private void OnOpen(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="Images|*.png;*.jpg;*.jpeg;*.bmp;*.webp|All files|*.*"};if(d.ShowDialog()!=true)return;_source=d.FileName;_points.Clear();_reference.Load(_source);_readout.Text="Click the first point, then the second point across the trim.";}
    private void Point(Point p){_points.Add(p);while(_points.Count>2)_points.RemoveAt(0);_readout.Text=_points.Count==1?$"First point: {p.X:0}, {p.Y:0}":$"Selected line: {_points[0].X:0}, {_points[0].Y:0} to {_points[1].X:0}, {_points[1].Y:0}";if(_points.Count==2)_=ProcessAsync();}
    private async Task ProcessAsync(){if(_source is null||_points.Count<2)return;try{var result=(await Context.Bridge.CallAsync("trim_process",new{path=_source,start=new[]{(int)_points[0].X,(int)_points[0].Y},end=new[]{(int)_points[1].X,(int)_points[1].Y},cropTop=0,cropBottom=0,correct=_correct.IsChecked==true}))!.AsObject();_current=result["path"]?.GetValue<string>();_preview.Load(_current);Status("Trim preview updated.");}catch(Exception ex){Error("Trim Creator",ex);}}
    private void OnStage(object s,RoutedEventArgs e){if(_current is null)return;_staged.Add((_current,_type.SelectedItem?.ToString()??"Collar Trim"));Refresh();}
    private void Refresh(){_list.ItemsSource=null;_list.ItemsSource=_staged.Select(x=>$"{x.Type} | {Path.GetFileName(x.Path)}").ToList();}
    private void OnSend(object s,RoutedEventArgs e){var keys=new Dictionary<string,string>{{"Collar Trim","collar_trim_image"},{"Left Arm Hole Trim","left_arm_hole_trim_image"},{"Right Arm Hole Trim","right_arm_hole_trim_image"},{"Waistband","waistband_image"}};foreach(var item in _staged)Context.Project.SetImage(keys[item.Type],item.Path);Status($"Sent {_staged.Count} staged trim(s) to Generator.");}
    private void LoadSelected(){if(_list.SelectedIndex<0)return;_current=_staged[_list.SelectedIndex].Path;_preview.Load(_current);}
    private void OnSave(object s,RoutedEventArgs e){if(_current is null)return;var d=new SaveFileDialog{Filter="PNG image|*.png",FileName="trim.png"};if(d.ShowDialog()==true)File.Copy(_current,d.FileName,true);}
    private void OnRemove(object s,RoutedEventArgs e){if(_list.SelectedIndex<0)return;_staged.RemoveAt(_list.SelectedIndex);Refresh();}
}

public sealed class TrimPathPage : ToolPageBase
{
    private readonly ImageViewport _view=new();private readonly TextBlock _readout=new(){Foreground=(System.Windows.Media.Brush)Application.Current.Resources["MutedBrush"]};private readonly ComboBox _shape=new();private readonly TextBox _width=new(){Text="64"};private readonly CheckBox _mirrorPanel=new(){Content="Create opposite-panel copy"},_mirrorX=new(){Content="Create X-axis mirror"};private readonly ListBox _layers=new();private readonly List<Point> _points=new();private string? _pattern;
    public TrimPathPage(WorkspaceContext context):base(context){_view.ImagePointClicked+=(_,p)=>Point(p);_view.ImageRightClicked+=(_,_)=>_=FinishAsync();var left=new Grid();left.RowDefinitions.Add(new RowDefinition());left.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});left.Children.Add(_view);Grid.SetRow(_readout,1);_readout.Margin=new Thickness(0,7,0,0);left.Children.Add(_readout);var right=new StackPanel();right.Children.Add(Ui.Button("Choose Trim Pattern",OnPattern,true));foreach(var item in new[]{"Straight segments","Smooth curve","T shape"})_shape.Items.Add(item);_shape.SelectedIndex=0;right.Children.Add(Ui.Row("Path shape",_shape));right.Children.Add(Ui.Row("Trim width",_width));right.Children.Add(_mirrorPanel);right.Children.Add(_mirrorX);right.Children.Add(Ui.Buttons(Ui.Button("Finish Path",async(_,_)=>await FinishAsync(),true),Ui.Button("Undo Point",(_,_)=>Undo())));right.Children.Add(Ui.Button("Clear Points",(_,_)=>{_points.Clear();Readout();}));_layers.Height=220;right.Children.Add(new GroupBox{Header="Generator Trim Paths",Content=_layers});right.Children.Add(Ui.Button("Remove Selected Layer",OnRemove));Content=Ui.Page("Trim Path Lab","Draw multi-point trim paths over the active generator texture. Right-click finishes a path; mirrors become separate movable layers.",Ui.Split(left,new ScrollViewer{Content=right,VerticalScrollBarVisibility=ScrollBarVisibility.Auto},360));Loaded+=async(_,_)=>await BackgroundAsync();RefreshLayers();}
    protected override async void OnProjectReplaced(){RefreshLayers();await BackgroundAsync();}
    private async Task BackgroundAsync(){try{var result=(await Context.Bridge.CallAsync("render",new{project=Context.Project.Snapshot(),kind="preview"}))!.AsObject();_view.Load(result["path"]?.GetValue<string>());}catch(Exception ex){Status(ex.Message);}}
    private void OnPattern(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="Trim PNG|*.png|Images|*.png;*.jpg;*.jpeg"};if(d.ShowDialog()==true){_pattern=d.FileName;Status($"Loaded trim pattern {Path.GetFileName(_pattern)}.");}}
    private void Point(Point p){if(_shape.SelectedItem?.ToString()=="T shape"&&_points.Count>=3)_points.Clear();_points.Add(p);Readout();}
    private void Readout(){var angle="--";if(_points.Count>1){var a=_points[^2];var b=_points[^1];angle=$"{Math.Atan2(b.Y-a.Y,b.X-a.X)*180/Math.PI:0.0} degrees";}_readout.Text=$"Points: {_points.Count} | Current angle: {angle} | Right-click to finish";}
    private void Undo(){if(_points.Count>0)_points.RemoveAt(_points.Count-1);Readout();}
    private async Task FinishAsync(){var needed=_shape.SelectedItem?.ToString()=="T shape"?3:2;if(_pattern is null||_points.Count<needed){Status($"Choose a trim and select at least {needed} points.");return;}try{var result=(await Context.Bridge.CallAsync("trim_path_render",new{pattern=_pattern,points=_points.Select(p=>new[]{p.X,p.Y}).ToArray(),shape=_shape.SelectedItem?.ToString(),trimWidth=int.TryParse(_width.Text,out var w)?w:64,mirrorPanel=_mirrorPanel.IsChecked==true,mirrorX=_mirrorX.IsChecked==true}))!.AsObject();var paths=result["paths"]!.AsArray();foreach(var path in paths){var array=(JsonArray)Context.Project.Generator["trimPathLayers"]!;var index=array.Count+1;array.Add(new JsonObject{{"name",$"Trim Path {index}"},{"path",path!.GetValue<string>()},{"garment",Context.Project.Garment},{"templateName",Context.Project.TemplateName},{"x",0},{"y",0},{"width",2048},{"height",2048},{"rotationDegrees",0},{"defaultX",0},{"defaultY",0},{"defaultWidth",2048},{"defaultHeight",2048}});}Context.Project.MarkChanged();_points.Clear();Readout();RefreshLayers();await BackgroundAsync();}catch(Exception ex){Error("Trim Path Lab",ex);}}
    private void RefreshLayers(){_layers.ItemsSource=null;_layers.ItemsSource=(Context.Project.Generator["trimPathLayers"] as JsonArray)?.Select(n=>$"{n?["name"]} | {n?["garment"]}").ToList();}
    private void OnRemove(object s,RoutedEventArgs e){if(_layers.SelectedIndex<0)return;((JsonArray)Context.Project.Generator["trimPathLayers"]!).RemoveAt(_layers.SelectedIndex);Context.Project.MarkChanged();RefreshLayers();}
}
