using System.Collections.ObjectModel;
using System.IO;
using System.Text.Json.Nodes;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Input;
using JerseyModder.Wpf.Controls;
using JerseyModder.Wpf.Services;
using Microsoft.Win32;

namespace JerseyModder.Wpf.Views;

public sealed class NumberEditorPage : ToolPageBase
{
    private readonly ImageViewport _preview=new();private readonly CheckBox _fillNone=new(){Content="No change",IsChecked=true},_outlineNone=new(){Content="No change",IsChecked=true};private readonly TextBox _fill=new(){Text="#ffffff"},_outline=new(){Text="#000000"};private readonly Slider _edge=new(){Minimum=0,Maximum=100,Value=0},_thickness=new(){Minimum=0,Maximum=20,Value=0};private readonly TextBlock _edgeText=new(){Text="0%"},_thicknessText=new(){Text="0 px"};private string? _source;
    public NumberEditorPage(WorkspaceContext context):base(context){var panel=new StackPanel();panel.Children.Add(Ui.Buttons(Ui.Button("Import Font IFF",OnOpen,true),Ui.Button("Browse Game Fonts",OnBrowse)));panel.Children.Add(Ui.Row("Fill",Pair(_fillNone,_fill)));panel.Children.Add(Ui.Row("Outline",Pair(_outlineNone,_outline)));panel.Children.Add(Ui.Row("Edge protection",Pair(_edge,_edgeText)));panel.Children.Add(Ui.Row("Outline thickness",Pair(_thickness,_thicknessText)));panel.Children.Add(Ui.Buttons(Ui.Button("Apply Recolor",OnApply,true),Ui.Button("Restore Original",async(_,_)=>await OpenAsync(_source))));panel.Children.Add(Ui.Button("Save Font IFF As",OnSave));_fill.TextChanged+=(_,_)=>{if(_fill.IsKeyboardFocusWithin)_fillNone.IsChecked=false;};_outline.TextChanged+=(_,_)=>{if(_outline.IsKeyboardFocusWithin)_outlineNone.IsChecked=false;};_edge.ValueChanged+=(_,_)=>_edgeText.Text=$"{_edge.Value:0}%";_thickness.ValueChanged+=(_,_)=>_thicknessText.Text=$"{_thickness.Value:0} px";Content=Ui.Page("Number Editor","Import or search a font IFF, recolor true fill and outline regions, then save a modified copy.",Ui.Split(_preview,new ScrollViewer{Content=panel,VerticalScrollBarVisibility=ScrollBarVisibility.Auto},430));}
    private static Grid Pair(UIElement a,UIElement b){var g=new Grid();g.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});g.ColumnDefinitions.Add(new ColumnDefinition());a.SetValue(FrameworkElement.MarginProperty,new Thickness(0,0,8,0));Grid.SetColumn(b,1);g.Children.Add(a);g.Children.Add(b);return g;}
    private void OnOpen(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="Font IFF|*font*.iff;*.iff|IFF|*.iff"};if(d.ShowDialog()==true)_=OpenAsync(d.FileName);}
    public async Task OpenAsync(string? path){if(string.IsNullOrWhiteSpace(path))return;try{var result=(await Context.Bridge.CallAsync("font_open",new{path}))!.AsObject();_source=result["source"]?.GetValue<string>();_preview.Load(result["preview"]?.GetValue<string>());Status($"Loaded {Path.GetFileName(_source)} ({result["width"]} x {result["height"]}).");}catch(Exception ex){Error("Number Editor",ex);}}
    private void OnBrowse(object s,RoutedEventArgs e){var window=new FontCatalogWindow(Context,async source=>await OpenAsync(source)){Owner=Window.GetWindow(this)};window.Show();}
    private void OnApply(object s,RoutedEventArgs e)=>_=RecolorAsync();
    private async Task RecolorAsync(){if(_source is null)return;try{var result=(await Context.Bridge.CallAsync("font_recolor",new{source=_source,fill=_fillNone.IsChecked==true?null:_fill.Text,outline=_outlineNone.IsChecked==true?null:_outline.Text,edge=(int)_edge.Value,thickness=(int)_thickness.Value}))!.AsObject();_preview.Load(result["path"]?.GetValue<string>());Status("Number recolor preview updated.");}catch(Exception ex){Error("Number Editor",ex);}}
    private async void OnSave(object s,RoutedEventArgs e){if(_source is null)return;var d=new SaveFileDialog{Filter="Font IFF|*.iff",FileName=Path.GetFileNameWithoutExtension(_source)+"_recolor.iff"};if(d.ShowDialog()!=true)return;try{await Context.Bridge.CallAsync("font_save",new{source=_source,destination=d.FileName,fill=_fillNone.IsChecked==true?null:_fill.Text,outline=_outlineNone.IsChecked==true?null:_outline.Text,edge=(int)_edge.Value,thickness=(int)_thickness.Value});Status($"Saved {Path.GetFileName(d.FileName)}.");}catch(Exception ex){Error("Number Editor",ex);}}
}

public sealed class FontCatalogWindow : Window
{
    private readonly WorkspaceContext _context;private readonly Func<string,Task> _load;private readonly ObservableCollection<FontEntry> _entries=new();private readonly DataGrid _grid=new(){AutoGenerateColumns=false,IsReadOnly=true,SelectionMode=DataGridSelectionMode.Single};private readonly ImageViewport _preview=new();private readonly TextBox _search=new();private readonly TextBlock _status=new();private string _root=@"C:\Program Files (x86)\Steam\steamapps\common\NBA 2K26";private CancellationTokenSource? _cacheCancel;
    private sealed class FontEntry{public string Team{get;init;}="";public string Uniform{get;init;}="";public string Name{get;init;}="";public string Archive{get;init;}="";public string Cached{get;set;}="";public JsonObject Raw{get;init;}=new();public string Terms=>$"{Team} {Uniform} {Name} {Archive}".ToLowerInvariant();}
    public FontCatalogWindow(WorkspaceContext context,Func<string,Task> load){_context=context;_load=load;Title="NBA 2K26 Game Fonts";Width=1220;Height=760;MinWidth=850;MinHeight=560;WindowStartupLocation=WindowStartupLocation.CenterOwner;
        _grid.Columns.Add(new DataGridTextColumn{Header="Team",Binding=new Binding("Team"),Width=150});_grid.Columns.Add(new DataGridTextColumn{Header="Uniform",Binding=new Binding("Uniform"),Width=150});_grid.Columns.Add(new DataGridTextColumn{Header="Font IFF",Binding=new Binding("Name"),Width=new DataGridLength(1,DataGridLengthUnitType.Star)});_grid.Columns.Add(new DataGridTextColumn{Header="Archive",Binding=new Binding("Archive"),Width=90});_grid.Columns.Add(new DataGridTextColumn{Header="Cached",Binding=new Binding("Cached"),Width=70});_grid.ItemsSource=_entries;_grid.SelectionChanged+=async(_,_)=>await PreviewAsync();_grid.MouseDoubleClick+=async(_,_)=>await LoadAsync();
        var root=new Grid{Margin=new Thickness(14)};root.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});root.RowDefinitions.Add(new RowDefinition());root.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});var top=new Grid{Margin=new Thickness(0,0,0,10)};top.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(90)});top.ColumnDefinitions.Add(new ColumnDefinition());top.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});top.Children.Add(new TextBlock{Text="Search",VerticalAlignment=VerticalAlignment.Center});Grid.SetColumn(_search,1);_search.Margin=new Thickness(0,0,8,0);_search.TextChanged+=(_,_)=>Filter();top.Children.Add(_search);var choose=Ui.Button("Choose Game Folder",async(_,_)=>await ChooseRoot());Grid.SetColumn(choose,2);top.Children.Add(choose);root.Children.Add(top);var split=Ui.Split(_grid,_preview,370);Grid.SetRow(split,1);root.Children.Add(split);var bottom=new Grid{Margin=new Thickness(0,10,0,0)};bottom.ColumnDefinitions.Add(new ColumnDefinition());bottom.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});bottom.Children.Add(_status);var actions=Ui.Buttons(Ui.Button("Cache Missing Previews",async(_,_)=>await CacheMissingAsync()),Ui.Button("Stop Cache",(_,_)=>_cacheCancel?.Cancel()),Ui.Button("Load in Number Editor",async(_,_)=>await LoadAsync(),true));Grid.SetColumn(actions,1);bottom.Children.Add(actions);Grid.SetRow(bottom,2);root.Children.Add(bottom);Content=root;Loaded+=async(_,_)=>await CatalogAsync();Closing+=(_,_)=>_cacheCancel?.Cancel();}
    private async Task ChooseRoot(){var d=new OpenFolderDialog{Title="Choose NBA 2K26 game folder",InitialDirectory=_root};if(d.ShowDialog(this)==true){_root=d.FolderName;await CatalogAsync();}}
    private async Task CatalogAsync(){try{_status.Text="Reading manifest and persistent preview cache...";var result=(await _context.Bridge.CallAsync("font_catalog",new{root=_root}))!.AsObject();_entries.Clear();foreach(var node in result["entries"]!.AsArray()){var o=node!.AsObject();_entries.Add(new FontEntry{Team=o["team"]?.GetValue<string>()??"",Uniform=o["uniform"]?.GetValue<string>()??"",Name=o["displayName"]?.GetValue<string>()??"",Archive=o["archive_id"]?.GetValue<string>()??"",Cached=o["cached"]?.GetValue<bool>()==true?"Yes":"",Raw=o});}_status.Text=$"{_entries.Count:N0} game fonts | {result["cached"]} cached previews.";}catch(Exception ex){MessageBox.Show(ex.Message,"Game Font Catalog");}}
    private void Filter(){var view=CollectionViewSource.GetDefaultView(_entries);var q=_search.Text.Trim().ToLowerInvariant();view.Filter=item=>string.IsNullOrEmpty(q)||((FontEntry)item).Terms.Contains(q);_status.Text=$"Showing {view.Cast<object>().Count():N0} of {_entries.Count:N0} fonts.";}
    private async Task PreviewAsync(){if(_grid.SelectedItem is not FontEntry item)return;try{var result=(await _context.Bridge.CallAsync("font_preview",new{root=_root,entry=item.Raw}))!.AsObject();_preview.Load(result["path"]?.GetValue<string>());_status.Text=result["label"]?.GetValue<string>()??item.Name;}catch(Exception ex){_status.Text=ex.Message;}}
    private async Task LoadAsync(){if(_grid.SelectedItem is not FontEntry item)return;try{_status.Text=$"Loading {item.Name}...";var result=(await _context.Bridge.CallAsync("font_open_manifest",new{root=_root,entry=item.Raw}))!.AsObject();var source=result["source"]!.GetValue<string>();await _load(source);_status.Text=$"Loaded {item.Name}.";}catch(Exception ex){MessageBox.Show(ex.Message,"Game Font Catalog");}}
    private async Task CacheMissingAsync(){var missing=_entries.Where(item=>item.Cached!="Yes").ToList();if(missing.Count==0){_status.Text="All manifest font previews are already cached.";return;}_cacheCancel?.Cancel();_cacheCancel=new CancellationTokenSource();var done=0;foreach(var item in missing){if(_cacheCancel.IsCancellationRequested)break;try{await _context.Bridge.CallAsync("font_preview",new{root=_root,entry=item.Raw},_cacheCancel.Token);item.Cached="Yes";}catch(OperationCanceledException){break;}catch{ }done++;if(done==1||done%5==0||done==missing.Count){_status.Text=$"Caching previews: {done:N0} of {missing.Count:N0}";_grid.Items.Refresh();}}_status.Text=_cacheCancel.IsCancellationRequested?$"Preview cache stopped: {done:N0} of {missing.Count:N0}.":$"Preview cache complete: {done:N0} of {missing.Count:N0}.";_grid.Items.Refresh();}
}

public sealed class TweakEditorPage : ToolPageBase
{
    private readonly Dictionary<string,TextBox> _values=new();private readonly CheckBox _lock=new(){Content="Lock width and height"};private string? _source;private bool _syncing;
    public TweakEditorPage(WorkspaceContext context):base(context){var panel=new StackPanel{MaxWidth=650,HorizontalAlignment=HorizontalAlignment.Left};panel.Children.Add(Ui.Buttons(Ui.Button("Import Tweak IFF",OnOpen,true),Ui.Button("Save Tweak IFF As",OnSave)));foreach(var item in new[]{("x","X position - left / right"),("y","Y position - down / up"),("width","Width - smaller / bigger"),("height","Height - smaller / bigger")}){var box=new TextBox{Width=180,HorizontalAlignment=HorizontalAlignment.Left};_values[item.Item1]=box;panel.Children.Add(Ui.Row(item.Item2,box));}panel.Children.Add(_lock);_values["width"].TextChanged+=(_,_)=>Lock("width","height");_values["height"].TextChanged+=(_,_)=>Lock("height","width");Content=Ui.Page("Tweak Editor","Adjust front jersey number position and size in clothing resource tweak IFF files.",panel);}
    private async void OnOpen(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="Tweak IFF|*tweak*.iff;*.iff|IFF|*.iff"};if(d.ShowDialog()!=true)return;try{var result=(await Context.Bridge.CallAsync("tweak_open",new{path=d.FileName}))!.AsObject();_source=d.FileName;foreach(var key in _values.Keys)_values[key].Text=result[key]?["value"]?.GetValue<double>().ToString("0.######")??"0";Status($"Loaded {Path.GetFileName(_source)}.");}catch(Exception ex){Error("Tweak Editor",ex);}}
    private void Lock(string from,string to){if(_syncing||_lock.IsChecked!=true)return;_syncing=true;_values[to].Text=_values[from].Text;_syncing=false;}
    private async void OnSave(object s,RoutedEventArgs e){if(_source is null)return;var d=new SaveFileDialog{Filter="Tweak IFF|*.iff",FileName=Path.GetFileNameWithoutExtension(_source)+"_edited.iff"};if(d.ShowDialog()!=true)return;try{double V(string k)=>double.Parse(_values[k].Text);await Context.Bridge.CallAsync("tweak_save",new{source=_source,destination=d.FileName,x=V("x"),y=V("y"),width=V("width"),height=V("height")});Status($"Saved {Path.GetFileName(d.FileName)}.");}catch(Exception ex){Error("Tweak Editor",ex);}}
}
